

GET http://localhost:8080/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWFhYSIsInVzZXJJZCI6IjUxYWM3ZTE5LTEyMWItNDU0Ni1iZjdlLTA3YzE0ZDdkMTRhMiIsImlhdCI6MTYzNTg5NDQzMiwiZXhwIjoxNjM1OTgwODMyfQ.LbVUeTFGeqhMhlhNxf8xebQMlaI0s-sBruLlvbz-_ew

###
POST http://localhost:8080/users
content-type: application/json

{
  "name":"aaaa",
  "password":"xxxx"
}

//・・・・・・・・・・invite


###
GET http://localhost:8080/users/invite/d9a47e64-7003-4eff-a74d-a7efa75f977f
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWFhYSIsInVzZXJJZCI6IjUxYWM3ZTE5LTEyMWItNDU0Ni1iZjdlLTA3YzE0ZDdkMTRhMiIsImlhdCI6MTYzNTc1NDExMCwiZXhwIjoxNjM1ODQwNTEwfQ.2UqxMoKKT5Td_MeEanD0VPSq__ZXhpOr5LktAxnHYGA

{
  "name":"yomeiTo",
  "password":"123456789"
}
###
POST http://localhost:8080/users/invite/21fad205-c473-4322-8fe8-4d0fba2074c9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWFhYSIsInVzZXJJZCI6IjUxYWM3ZTE5LTEyMWItNDU0Ni1iZjdlLTA3YzE0ZDdkMTRhMiIsImlhdCI6MTYzNTg5NDQzMiwiZXhwIjoxNjM1OTgwODMyfQ.LbVUeTFGeqhMhlhNxf8xebQMlaI0s-sBruLlvbz-_ew

###
POST http://localhost:8080/users/invite/reply/f63e3c50-4a53-4527-9164-b5bfbab8e55f
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoieW9tZWlUbyIsInVzZXJJZCI6ImQ5YTQ3ZTY0LTcwMDMtNGVmZi1hNzRkLWE3ZWZhNzVmOTc3ZiIsImlhdCI6MTYzNTQxMjEwMSwiZXhwIjoxNjM1NDk4NTAxfQ.wxhWc6E5ZIdVM7lfjmNHo_ZeR_eO-3DVlWJFexFdZC4

{
  "isAccept": true
}
