
GET http://localhost:8080/invite

###
GET http://localhost:8080/invite/a02a48bd-52c9-45d2-a032-69652e906846
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoieW9tZWkiLCJ1c2VySWQiOiI5NDE0OWE4MC03ZDg5LTRjYTctODllYy1jMjk4ZmM3ZTYyYjciLCJpYXQiOjE2MzUzMDI4ODksImV4cCI6MTYzNTM4OTI4OX0.Tn6IO7DyUqGh1LuvYA7P-Jrz_rlGulv0w51iWzM0s9w

###
POST http://localhost:8080/invite
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoieW9tZWkiLCJ1c2VySWQiOiJhZWM5OTZmYS1hOGQ5LTQ5OTEtYjZlZS0wZjdkYWYxNDg0YTMiLCJpYXQiOjE2MzUzMDY1NjQsImV4cCI6MTYzNTM5Mjk2NH0.CZt8kLxJPyhTk_FyKICQiN7K8pNczw5m_JnnxHxaxqY

{
  "content": "Chat!!!!!!!!!!!!!",
  "userId": "aec996fa-a8d9-4991-b6ee-0f7daf1484a3",
  "roomId": "8f04e552-8dae-4e38-94ad-7568d3c04015"
}
